services:
  backend:
    image: 237024525392.dkr.ecr.ap-south-1.amazonaws.com/${ECR_BACKEND_REPO}:latest
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"

  frontend:
    image: 237024525392.dkr.ecr.ap-south-1.amazonaws.com/${ECR_FRONTEND_REPO}:latest
    restart: unless-stopped
    ports:
      - "3001:3000"
    depends_on:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db-migration-ec2.c9ug64u4komr.ap-south-1.rds.amazonaws.com
      PMA_PORT: 3306
    ports:
      - "8080:80"
