services:
  backend:
    image: 237024525392.dkr.ecr.ap-south-1.amazonaws.com/docker-test-backend:staging
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"

  frontend:
    image: 237024525392.dkr.ecr.ap-south-1.amazonaws.com/docker-test-frontend:staging
    restart: unless-stopped
    ports:
      - "3001:3000"
    depends_on:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_PORT: ${PMA_PORT:-3306}
    ports:
      - "8080:80"
